import React from 'react';
import {needs} from './Needs';

export default function Completion({screen,feeling,need,thought,headingRef,onBack,onFinish,onRestart}){
 const restart=screen==='restart';
 const takeaway=need==='rest'?'คุณให้เวลาตัวเองหยุดและสังเกตสิ่งรอบตัว':need==='think'?(thought||'ค่อย ๆ ดูทีละเรื่องก็พอ'):'เริ่มจากข้อความเล็ก ๆ';
 return <div className={`check-in-content completion-content ${restart?'restart-content':'summary-content'}`}>
  <div className="check-in-heading"><div className="needs-topline"><p className="eyebrow">{restart?'A MOMENT FOR YOU':'YOUR LITTLE TAKEAWAY'}</p>{!restart&&<button className="back-button" onClick={onBack}><img src="/assets/back-arrow.svg" alt=""/>ย้อนกลับ</button>}</div><h1 ref={headingRef} tabIndex={-1}>{restart?'ขอบคุณที่ให้เวลากับตัวเอง':'สิ่งเล็ก ๆ ที่คุณได้พกกลับไป'}</h1><p className="description">{restart?'จะรู้สึกเหมือนเดิมหรือต่างไป ก็ไม่ต้องรีบหาคำตอบให้ทุกอย่าง':'นี่คือสิ่งที่คุณเลือกให้ตัวเองในช่วงพักนี้'}</p></div>
  {restart?<><div className="restart-panel"><div className="rest-illustration" aria-hidden="true"><img className="rest-inner-circle" src="/assets/rest-inner-circle.svg" alt=""/><img className="rest-outer-circle" src="/assets/rest-outer-circle.svg" alt=""/><img className="rest-happy" src="/assets/mooca-happy.svg" alt=""/></div><div className="restart-copy"><h2>ขอบคุณที่แวะมาฟังตัวเองในวันนี้</h2><p>คุณกลับมาพักตรงนี้ได้เสมอ</p></div></div><div className="rest-buttons"><button className="continue" onClick={onRestart}><span className="restart-icon"><img src="/assets/restart-icon.svg" alt=""/></span>เริ่มช่วงพักใหม่อีกครั้ง</button><a className="skip-button consultation-link" href="https://ooca.co/" target="_blank" rel="noreferrer">ดูทางเลือกการปรึกษากับ ooca</a></div></>:<><div className="summary-panel"><p className="summary-caption"><img src="/assets/imgIconFavoriteRegular.svg" alt=""/>ช่วงพักของคุณ</p><dl><div><dt>ฉันรู้สึก</dt><dd>{feeling.label}</dd></div><div><dt>ฉันต้องการ</dt><dd>{needs.find(n=>n.id===need)?.title}</dd></div></dl><div className="summary-divider"/><p className="summary-caption">สิ่งที่ฉันเลือกให้ตัวเอง</p><p className="takeaway">{takeaway}</p></div><div className="summary-actions"><div className="summary-note"><p>ไม่จำเป็นต้องรู้สึกดีขึ้นทันที</p><p>การได้ฟังตัวเองก็เป็นช่วงเวลาที่มีความหมายได้</p></div><button className="continue" onClick={onFinish}>จบช่วงพักนี้<img src="/assets/imgIconArrowSmallRight.svg" alt=""/></button><a className="skip-button consultation-link" href="https://ooca.co/" target="_blank" rel="noreferrer">อยากมีคนรับฟังต่อ? ดูการปรึกษากับ ooca</a></div></>}
 </div>;
}
